spectaql:
  logoFile: /static/images/logo.png
  faviconFile: /static/images/favicon.ico

introspection:
  schemaFile: ./core/api/src/graphql/admin/schema.graphql

info:
  title: GraphQL Admin API Reference
  description: Welcome to the Blink Admin API reference!
  contact:
    name: Blink developer community
    url: https://chat.blink.sv/
  license:
    name: MIT
    url: https://opensource.org/licenses/MIT

servers:
  - url: https://admin-api.staging.blink.sv/graphql
    description: Signet
    production: false
